### ISSUE TITLE
User registration and contact form broken on graphviz.org

### ISSUE THREAD

**Issue by Liam-Ryan** [ellson/MOTHBALLED-graphviz#1270]
Apologies for posting in the repo but I'm unable to register as a new user or contact the site admin using contact us on graphviz.org as the back-end seems to be down ( www.graphviz.org:8080) 

I'm hoping someone who manages the repo has contact details for the site admin.

**Comment by emden** [comment]
Actually, we have been in the process of moving the Graphviz web site to github, precisely because the current site has become unreliable. If you have questions or issues or bugs, use the Issues tab to report these.

**Comment by Liam-Ryan** [comment]
Thanks I'm pretty sure it's a problem with my setup I didn't want to raise an issue if I could help it. I posted on SO - https://stackoverflow.com/questions/45788136/graphviz-could-not-load-gvplugin-pango-dll

**Comment by magjac** [comment]
I'm also having trouble with new user registration. Under [Contacts](https://github.com/ellson/graphviz#contacts) you refer to the [user forum](http://www.graphviz.org/forums/general-discussion), but without the possibility to register a new user, I cannot participate. Is there any recommended alternative?

**Comment by emden** [comment]
We haven't updated that info yet. Thanks for pointing it out. As I mentioned above, just use the Issues page on github.

**Comment by magjac** [comment]
Thanks. I will do that.
