### ISSUE TITLE
How to build static executable dot with all dependencies?

### ISSUE THREAD

**Issue by Atsman** [ellson/MOTHBALLED-graphviz#1271]
Hi, i want to use graphviz in AWS lambda environment. I can't use package managers, because environment clean all things frequently. So i want to build static executable and place it in source files of my project. 

Here is what i have done already:
```
$ // Rent ec2 instance.
$ // Connect to it using ssh.
$ yum groupinstall "Development tools" // that will install C compiler and delepment tools.
$ sudo yum install cairo-devel pango-devel // that dependencies required for PDF format.
$ wget http://www.graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.40.1.tar.gz
$ tar -xvf graphviz-2.40.1.tar.gz
$ cd graphviz-2.40.1
$ ./configure 
$ make 
$ cd cmd/dot
$ make dot_static
```

After that i packed dot_static in my Clojure application and call it programmatically. I want to generate pdf files.

Now i receive next error - `"/tmp/dot_static: error while loading shared libraries: libpangocairo-1.0.so.0: cannot open shared object file: No such file or directory"`.

So my question is - is it possible to somehow build lib fully packed with all it dependencies? So that it can be passed as one executable file and can generate pdf files?

Thank you.

**Comment by ellson** [comment]
You will need ./configure --enable-static

but this still only links in code from within the graphviz tree into a single binary, without dynamic loading.

External libraries such as libc, or libpangocairo, or libpoppler are still loaded from their .so

l

**Comment by Atsman** [comment]
@ellson so is it impossible to compile graphviz with all external dependencies? Can i place those .so files near executable file so it can find it?

**Comment by ellson** [comment]
> @ellson so is it impossible to compile graphviz with all external dependencies?

The Redhat distributions don't provide statically linkable .a files for graphviz to link against, so basically yes.

> Can I place those .so files near executable file so it can find it?

That might work. You will also need the further dependencies of the .so libraries, use ldd to check ...e.g.

$ ldd /usr/lib64/libpangocairo-1.0.so
linux-vdso.so.1 (0x00007ffd3aba4000)
libcairo.so.2 => /lib64/libcairo.so.2 (0x00007fb050b81000)
libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007fb05096c000)
libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007fb05071f000)
libthai.so.0 => /lib64/libthai.so.0 (0x00007fb050515000)
libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007fb0502c3000)
libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007fb0500c1000)
libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007fb04fdae000)
libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007fb04fb19000)
libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007fb04f8d5000)
libm.so.6 => /lib64/libm.so.6 (0x00007fb04f5bf000)
libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007fb04f30f000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb04f0f0000)
libc.so.6 => /lib64/libc.so.6 (0x00007fb04ed1f000)
libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007fb04ea7a000)
libEGL.so.1 => /lib64/libEGL.so.1 (0x00007fb04e867000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007fb04e663000)
libpng16.so.16 => /lib64/libpng16.so.16 (0x00007fb04e430000)
libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007fb04e22c000)
libxcb.so.1 => /lib64/libxcb.so.1 (0x00007fb04e004000)
libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007fb04ddf6000)
libXrender.so.1 => /lib64/libXrender.so.1 (0x00007fb04dbec000)
libX11.so.6 => /lib64/libX11.so.6 (0x00007fb04d8ae000)
libXext.so.6 => /lib64/libXext.so.6 (0x00007fb04d69c000)
libz.so.1 => /lib64/libz.so.1 (0x00007fb04d485000)
libGL.so.1 => /lib64/libGL.so.1 (0x00007fb04d1f9000)
librt.so.1 => /lib64/librt.so.1 (0x00007fb04cff1000)
libdatrie.so.1 => /lib64/libdatrie.so.1 (0x00007fb04cdea000)
libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fb04cb77000)
libffi.so.6 => /lib64/libffi.so.6 (0x00007fb04c96f000)
libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007fb04c743000)
libexpat.so.1 => /lib64/libexpat.so.1 (0x00007fb04c510000)
/lib64/ld-linux-x86-64.so.2 (0x00007fb0510b6000)
libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fb04c300000)
libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007fb04c04a000)
libXau.so.6 => /lib64/libXau.so.6 (0x00007fb04be46000)
libGLX.so.0 => /lib64/libGLX.so.0 (0x00007fb04bc14000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb04b9fd000)


Do you see the reason for package managers now?

Good luck!

**Comment by szymonkochanski** [comment]
> i want to use graphviz in AWS lambda environment
@Atsman, any success? I want to do the same.

**Comment by Atsman** [comment]
@szymonkochanski hi, please check this out https://github.com/Atsman/clj-lambda-graphviz-s3
