### ISSUE TITLE
how to custom layout

### ISSUE THREAD

**Issue by helloyi** [ellson/MOTHBALLED-graphviz#1283]
Hi!
1.  I want to code a draw internal-DSL with Python.
2. And easy to draw graph(mem-struct, data-struct, flow-chat...), and used in org babel, my original intention.
3. How to custom layout module?

thx a lot!

**Comment by ellson** [comment]
You will need to expand your question a bit so I can better understand what you are looking for.

Are you looking for a different graph layout engine, like dot (directed graphs), neato (undirected graphs), ...

Or are you looking to render a layout to a different output, like png, pdf, svg, ...

Can you point me to some examples of "internal-DSL" ? Maybe even some hand-drawn examples of expected output?

Are you familiar with doxygen's use of graphviz for diagramming: class-inheritance, include trees, call-graphs, ... ?
Are you looking to do something like that?

John

**Comment by helloyi** [comment]
1. I mean to customize a layout engine, that organize nodes in a specific way.
2. It's like `pantuml`,  the difference is:
    + internal-DSL with python
    + composite structure of the node (e.g. mem-struct, data-struct, ...)

    ```python
       # `Brush` can draw some specific shape on `Canvas`
       struct_node = pstruct.paint("the struct node name", ["field1", ["field2-1", "..."]])
       array_node = parray.paint("the array node name", ["elem1", "..."]
       pedge.paint(struct_node["field1"], array_node["elem1"])
       # etc.
       
       # `Layout` can organize "nodes"
       # Such as to provide a grid model interface for uses
       gridLayout.grid[0][0] = node1
       gridLayout.grid[2][2] = node2
       # Or a coordinate model
       coordLayout.setZeroPont(node1)
       coordLayout.coord[x][y] = node2
       # Or a path model
       pathLayout.path(x1, y1, x2, y2).nodes(node1, node2, ...)

       # `Painter` can draw "flowchart", "class chart", etc.
       # `Painter`'s implementation is based on `Brush`,  `Layout` and `Canvas`
       fc = PFlowchart()
       fc.start().
           process("abc").
           if_("n>1").then(
                 fc.process('then_p1')
                     .process('then_p2')).
            else_(
                 fc.process('e_p1')
                    .process('e_p2')).
           endif().
           end()
   ```

3. Focus on the layout model
![grid model](https://user-images.githubusercontent.com/5888524/30772385-4492969a-a08c-11e7-93fe-92d214cbdc3e.png)
![coord model](https://user-images.githubusercontent.com/5888524/30772381-2ff2cfca-a08c-11e7-88b3-eef3287ab6a4.png)
![path model](https://user-images.githubusercontent.com/5888524/30772383-3849bfa8-a08c-11e7-8719-1a0396e7b48d.png)

Thx a lot!

**Comment by emden** [comment]
You can use the various node attributes, especially HTML-like labels to tailor the nodes to your needs. You then need to write code to do the new layouts. This is described  [here](https://graphviz.gitlab.io/_pages/doc/addingLayout.txt). The rendering is handled automatically.

**Comment by helloyi** [comment]
I understand.
Thanks a lot!

**Comment by emden** [comment]
If you have any questions, feel free to ask here.
