### ISSUE TITLE
dot error

### ISSUE THREAD

**Issue by wmmw123** [ellson/MOTHBALLED-graphviz#1290]
Hello,

I have a question ...

When you run dot, my  prompted to run the -c option.

However, I do not have permission to use sudo

Is there a way to fix it?

Thanks.

```
There is no layout engine support for "dot"
Perhaps "dot -c" needs to be run (with installer's privileges) to register the plugins?
```

**Comment by emden** [comment]
dot -c is going to write a file in the same directory where the plugins were written, so if those were installed, you don't need sudo to write there. Just run dot -c.

**Comment by johnnybaloney** [comment]
Is there a way to tell `dot` where the plugins were written to? I built it from [source](https://graphviz.gitlab.io/_pages/Download/Download_source.html) and also don't have root access, running `/.dot -c` doesn't help.

**Comment by magneticnorth** [comment]
Generally the locations of the plugins is $prefix/lib/graphviz and prefix is set by you when you run the configure script.  

I always build with  ./configure —prefix=$HOME and it works fine.

**Comment by emden** [comment]
You can also run dot -v. You'll see something like

libdir = "/Users/erg/lib/graphviz

**Comment by johnnybaloney** [comment]
`./configure --prefix /some/path` followed by `make install` worked their magic. Thank you! :trophy:
